#!/usr/bin/python

import os
from optparse import OptionParser

from LanguageSelector import FontConfig


def main():
    usage = "usage: %prog [options] arg"
    parser = OptionParser(usage)
    parser.add_option("-f", "--force", dest="force",
                      action="store_true")
    #parser.add_option("-v", "--verbose",
    #                  action="store_true", dest="verbose")
    (options, args) = parser.parse_args()
    if len(args) != 0:
        parser.error("incorrect number of arguments")

    fc = FontConfig.FontConfigHack()
    if not os.path.exists(fc.configFile) or options.force:
        res = fc.setConfigBasedOnLocale()
    
if __name__ == "__main__":
    main()
