#!/usr/bin/python2.4


import pygtk
pygtk.require("2.0")
import gtk
import gtk.glade

import gettext
import sys
import os

from LanguageSelector.LanguageSelector import LanguageSelector
from gettext import gettext as _

if __name__ == "__main__":
        gettext.bindtextdomain("language-selector", "/usr/share/locale")
        gettext.textdomain("language-selector")
        gtk.glade.bindtextdomain("language-selector", "/usr/share/locale")
        gtk.glade.textdomain("language-selector")

	if os.getuid() != 0:
            d = gtk.MessageDialog(flags=gtk.DIALOG_MODAL,
                                  type=gtk.MESSAGE_ERROR,
                                  buttons=gtk.BUTTONS_CLOSE)
            d.set_markup("<big><b>%s</b></big>\n\n%s" % (
                _("You are not root"),
                _("Please run this software with administrative rights.")))
            d.set_title("")
            d.run()
            d.destroy()
            sys.exit(1)

	app = LanguageSelector(datadir="/usr/share/language-selector/")
	app.run()
